/**
 * Canonical RBAC matrix used by seed data and authorization tests.
 * Permissions are resource:action pairs.
 */

export const PERMISSION_ACTIONS = [
  'view',
  'create',
  'update',
  'delete',
  'publish',
  'archive',
  'cancel',
  'moderate',
  'assign',
  'approve',
  'manage',
  'import',
  'export',
] as const;

export const PERMISSION_RESOURCES = [
  'users',
  'roles',
  'permissions',
  'church',
  'leadership',
  'governance',
  'ministries',
  'staff',
  'volunteers',
  'content',
  'events',
  'sermons',
  'prayer',
  'media',
  'gallery',
  'members',
  'pastoral',
  'attendance',
  'giving',
  'communications',
  'finance',
  'settings',
  'security_logs',
  'profile',
] as const;

export type PermissionAction = (typeof PERMISSION_ACTIONS)[number];
export type PermissionResource = (typeof PERMISSION_RESOURCES)[number];
export type PermissionKey = `${PermissionResource}:${PermissionAction}`;

export interface RoleDefinition {
  slug: string;
  name: string;
  description: string;
  hierarchy: number;
  isPrivileged: boolean;
  permissions: PermissionKey[] | 'all';
}

function allPermissions(): PermissionKey[] {
  const keys: PermissionKey[] = [];
  for (const resource of PERMISSION_RESOURCES) {
    for (const action of PERMISSION_ACTIONS) {
      keys.push(`${resource}:${action}`);
    }
  }
  return keys;
}

const PROFILE: PermissionKey[] = ['profile:view', 'profile:update'];
const PUBLIC_MEMBER_CONTENT: PermissionKey[] = [
  'content:view',
  'events:view',
  'sermons:view',
  'prayer:create',
];

export const ROLE_DEFINITIONS: RoleDefinition[] = [
  {
    slug: 'super_admin',
    name: 'Super Administrator',
    description: 'Highest privilege. Manages administrators, roles, permissions, and system settings.',
    hierarchy: 100,
    isPrivileged: true,
    permissions: 'all',
  },
  {
    slug: 'admin',
    name: 'Administrator',
    description: 'Manages church information, leadership, ministries, users, and content. Cannot elevate to Super Administrator.',
    hierarchy: 80,
    isPrivileged: true,
    permissions: [
      ...PROFILE,
      'users:view',
      'users:create',
      'users:update',
      'users:manage',
      'roles:view',
      'permissions:view',
      'church:view',
      'church:create',
      'church:update',
      'church:delete',
      'church:publish',
      'church:archive',
      'church:manage',
      'leadership:view',
      'leadership:create',
      'leadership:update',
      'leadership:delete',
      'leadership:manage',
      'governance:view',
      'governance:create',
      'governance:update',
      'governance:delete',
      'governance:approve',
      'governance:assign',
      'governance:manage',
      'governance:export',
      'ministries:view',
      'ministries:create',
      'ministries:update',
      'ministries:delete',
      'ministries:manage',
      'ministries:assign',
      'ministries:moderate',
      'staff:view',
      'staff:create',
      'staff:update',
      'staff:archive',
      'staff:manage',
      'volunteers:view',
      'volunteers:create',
      'volunteers:update',
      'volunteers:approve',
      'volunteers:manage',
      'content:view',
      'content:create',
      'content:update',
      'content:delete',
      'content:publish',
      'content:archive',
      'content:manage',
      'events:view',
      'events:create',
      'events:update',
      'events:delete',
      'events:publish',
      'events:archive',
      'events:cancel',
      'events:assign',
      'events:moderate',
      'events:manage',
      'sermons:view',
      'sermons:create',
      'sermons:update',
      'sermons:delete',
      'sermons:publish',
      'sermons:archive',
      'sermons:manage',
      'prayer:view',
      'prayer:create',
      'prayer:update',
      'prayer:moderate',
      'prayer:assign',
      'prayer:archive',
      'prayer:manage',
      'media:view',
      'media:create',
      'media:update',
      'media:delete',
      'media:publish',
      'media:manage',
      'gallery:view',
      'gallery:create',
      'gallery:update',
      'gallery:delete',
      'gallery:publish',
      'gallery:archive',
      'gallery:manage',
      'members:view',
      'members:create',
      'members:update',
      'members:archive',
      'members:approve',
      'members:moderate',
      'members:manage',
      'members:import',
      'members:export',
      // Admin: overview only — not unrestricted note access (pastoral:moderate required for notes)
      'pastoral:view',
      'pastoral:create',
      'pastoral:update',
      'pastoral:assign',
      'attendance:view',
      'attendance:create',
      'attendance:update',
      'attendance:moderate',
      'attendance:archive',
      'attendance:assign',
      'attendance:manage',
      'giving:view',
      'giving:create',
      'giving:update',
      'giving:publish',
      'giving:moderate',
      'giving:cancel',
      'giving:manage',
      'communications:view',
      'communications:create',
      'communications:update',
      'communications:publish',
      'communications:moderate',
      'communications:assign',
      'communications:manage',
      'finance:view',
      'finance:create',
      'finance:update',
      'finance:moderate',
      'finance:manage',
      'settings:view',
    ],
  },
  {
    slug: 'pastor',
    name: 'Pastor',
    description: 'Pastoral leadership over church content, ministries, and congregation care.',
    hierarchy: 70,
    isPrivileged: false,
    permissions: [
      ...PROFILE,
      'users:view',
      'church:view',
      'church:update',
      'leadership:view',
      'leadership:update',
      'governance:view',
      'governance:create',
      'governance:update',
      'governance:approve',
      'governance:assign',
      'governance:manage',
      'ministries:view',
      'ministries:update',
      'ministries:assign',
      'staff:view',
      'volunteers:view',
      'volunteers:approve',
      'content:view',
      'content:create',
      'content:update',
      'content:publish',
      'events:view',
      'events:create',
      'events:update',
      'events:publish',
      'events:archive',
      'events:cancel',
      'events:assign',
      'events:moderate',
      'sermons:view',
      'sermons:create',
      'sermons:update',
      'sermons:publish',
      'sermons:archive',
      'prayer:view',
      'prayer:create',
      'prayer:update',
      'prayer:moderate',
      'prayer:assign',
      'prayer:archive',
      'media:view',
      'gallery:view',
      'gallery:update',
      'gallery:publish',
      'gallery:archive',
      'members:view',
      'members:update',
      'members:approve',
      'members:moderate',
      'members:archive',
      'pastoral:view',
      'pastoral:create',
      'pastoral:update',
      'pastoral:assign',
      'pastoral:moderate',
      'pastoral:manage',
      'pastoral:archive',
      'attendance:view',
      'attendance:create',
      'attendance:update',
      'attendance:moderate',
      'attendance:archive',
      'attendance:assign',
      'giving:view',
      'communications:view',
      'communications:create',
      'communications:update',
      'communications:publish',
      'communications:assign',
    ],
  },
  {
    slug: 'church_leader',
    name: 'Church Leader',
    description: 'Supports church leadership, events, and announcements.',
    hierarchy: 60,
    isPrivileged: false,
    permissions: [
      ...PROFILE,
      'church:view',
      'leadership:view',
      'leadership:update',
      'governance:view',
      'governance:create',
      'governance:update',
      'governance:approve',
      'governance:assign',
      'ministries:view',
      'content:view',
      'content:create',
      'content:update',
      'events:view',
      'events:create',
      'events:update',
      'events:assign',
      'sermons:view',
      'prayer:view',
      'gallery:view',
      'members:view',
      'attendance:view',
      'attendance:create',
      'attendance:update',
      'communications:view',
      'communications:create',
      'communications:update',
      'communications:publish',
      'communications:assign',
    ],
  },
  {
    slug: 'ministry_leader',
    name: 'Ministry Leader',
    description: 'Manages assigned ministry content. Cannot manage users, finance, or other ministries by default.',
    hierarchy: 50,
    isPrivileged: false,
    permissions: [
      ...PROFILE,
      'ministries:view',
      'ministries:update',
      'ministries:assign',
      'ministries:moderate',
      'volunteers:view',
      'volunteers:update',
      'volunteers:approve',
      'content:view',
      'content:create',
      'content:update',
      'events:view',
      'events:create',
      'events:update',
      'events:assign',
      'members:view',
      'attendance:view',
      'attendance:create',
      'attendance:update',
      'communications:view',
      'communications:create',
      'communications:assign',
    ],
  },
  {
    slug: 'volunteer_coordinator',
    name: 'Volunteer Coordinator',
    description: 'Reviews volunteer applications and manages service assignments across authorized ministries.',
    hierarchy: 48,
    isPrivileged: false,
    permissions: [
      ...PROFILE,
      'ministries:view',
      'ministries:assign',
      'volunteers:view',
      'volunteers:create',
      'volunteers:update',
      'volunteers:approve',
      'volunteers:manage',
      'members:view',
      'events:view',
      'events:assign',
      'communications:view',
      'communications:create',
      'communications:assign',
    ],
  },
  {
    slug: 'media_team',
    name: 'Media Team',
    description: 'Manages media, sermons presentation, and published visual content.',
    hierarchy: 40,
    isPrivileged: false,
    permissions: [
      ...PROFILE,
      'media:view',
      'media:create',
      'media:update',
      'media:delete',
      'media:publish',
      'media:manage',
      'sermons:view',
      'sermons:create',
      'sermons:update',
      'sermons:publish',
      'content:view',
      'content:update',
      'gallery:view',
      'gallery:create',
      'gallery:update',
      'gallery:delete',
    ],
  },
  {
    slug: 'prayer_team',
    name: 'Prayer Team',
    description: 'Accesses prayer requests. Cannot access financial records or system configuration.',
    hierarchy: 40,
    isPrivileged: false,
    permissions: [
      ...PROFILE,
      'prayer:view',
      'prayer:create',
      'prayer:update',
    ],
  },
  {
    slug: 'pastoral_care',
    name: 'Pastoral Care Staff',
    description: 'Manages assigned pastoral care cases, visits, and follow-ups. Notes require pastoral:moderate.',
    hierarchy: 55,
    isPrivileged: false,
    permissions: [
      ...PROFILE,
      'members:view',
      'prayer:view',
      'prayer:create',
      'prayer:update',
      'pastoral:view',
      'pastoral:create',
      'pastoral:update',
      'pastoral:assign',
      'pastoral:moderate',
      'communications:view',
      'communications:create',
      'communications:assign',
    ],
  },
  {
    slug: 'finance',
    name: 'Finance',
    description: 'Accesses giving and financial reports. Cannot access prayer requests or authentication secrets.',
    hierarchy: 50,
    isPrivileged: true,
    permissions: [
      ...PROFILE,
      'giving:view',
      'giving:create',
      'giving:update',
      'giving:publish',
      'giving:moderate',
      'giving:cancel',
      'giving:manage',
      'finance:view',
      'finance:create',
      'finance:update',
      'finance:moderate',
      'finance:manage',
    ],
  },
  {
    slug: 'member',
    name: 'Member',
    description: 'Default role for registered accounts. Own profile and permitted member content.',
    hierarchy: 10,
    isPrivileged: false,
    permissions: [...PROFILE, ...PUBLIC_MEMBER_CONTENT],
  },
  {
    slug: 'finance_auditor',
    name: 'Finance Auditor',
    description: 'Read-only access to financial records and reports. Cannot approve expenses or issue refunds.',
    hierarchy: 45,
    isPrivileged: true,
    permissions: [
      ...PROFILE,
      'giving:view',
      'finance:view',
    ],
  },
];

export function permissionsForRole(slug: string): PermissionKey[] {
  const role = ROLE_DEFINITIONS.find((r) => r.slug === slug);
  if (!role) return [];
  if (role.permissions === 'all') return allPermissions();
  return role.permissions;
}

export function parsePermissionKey(key: PermissionKey): {
  resource: PermissionResource;
  action: PermissionAction;
} {
  const [resource, action] = key.split(':') as [PermissionResource, PermissionAction];
  return { resource, action };
}

export function allPermissionKeys(): PermissionKey[] {
  return allPermissions();
}
